// sync
export const SELECT_ACTIVE_REGISTER_FORM = 'SELECT_ACTIVE_REGISTER_FORM';
export const SELECT_ACTIVE_LOGIN_FORM = 'SELECT_ACTIVE_LOGIN_FORM';

// async
// export const REGISTER_USER_ASYNC = 'REGISTER_USER_ASYNC';